Repository wooga/atlas-unity, pull requests merged in 2021-07, with the labels that each got.

#104 Updated atlas plugin to 2.2.0
  Jenkinsfile
  build.gradle
Labels: atlas-stream, new, update

#106 Add more of the supported command line options for Unity's Test Frame…
  src/main/groovy/wooga/gradle/unity/models/UnityCommandLineOption.groovy
  src/main/groovy/wooga/gradle/unity/traits/UnityCommandLineSpec.groovy
Labels: atlas-stream, update

#107 Refactor how the values of properties in integration tests are queried
  src/integrationTest/groovy/wooga/gradle/IntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/unity/UnityIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/unity/UnityPluginIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/utils/PropertyQueryTaskWriter.groovy
  src/integrationTest/groovy/wooga/gradle/utils/PropertyUtils.groovy
  src/main/groovy/wooga/gradle/unity/tasks/Activate.groovy
Labels: add, atlas-stream, improve, update
