Repository wooga/atlas-unity, pull requests merged in 2021-06, with the labels that each got.

#93 Update gradle to 6.9 and net.wooga.plugins to 2.1.1
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradle_check_versions.sh
Labels: atlas-stream, gradle, update

#94 Skip SetAPICompLevel task if the project settings file is not present
  src/main/groovy/wooga/gradle/unity/tasks/SetAPICompatibilityLevel.groovy
Labels: atlas-stream

#97 Fix remove default BuildTarget.undefined
  src/integrationTest/groovy/wooga/gradle/unity/UnityPluginIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
  src/main/groovy/wooga/gradle/unity/UnityPluginExtension.groovy
  src/main/groovy/wooga/gradle/unity/models/BuildTarget.groovy
Labels: atlas-stream, fix

#96 Fix license directory Linux check
  build.gradle
  src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
  src/main/groovy/wooga/gradle/unity/UnityPluginConventions.groovy
  src/main/groovy/wooga/gradle/unity/utils/PlatformUtils.groovy
Labels: atlas-stream, update

#98 Unity Task environment setter
  src/integrationTest/groovy/wooga/gradle/unity/UnityIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/unity/UnityTask.groovy
  src/main/groovy/wooga/gradle/unity/traits/ArgumentsSpec.groovy
Labels: atlas-stream, update

#99 Fix the environment initialization in UnityTask
  src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/unity/UnityTask.groovy
Labels: atlas-stream, fix

#102 Fix default environment for Unity invocation
  src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
Labels: atlas-stream, fix
