Repository wooga/atlas-unity, pull requests merged in 2021-09, with the labels that each got.

#118 FIx: Coverage version floor comparison
  src/integrationTest/groovy/wooga/gradle/unity/tasks/TestTaskIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/unity/tasks/Test.groovy
Labels: fix, atlas-stream

#116 Add missing getters for unity task command line options
  src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/utils/PropertyQueryTaskWriter.groovy
  src/integrationTest/groovy/wooga/gradle/utils/PropertyUtils.groovy
  src/main/groovy/wooga/gradle/unity/traits/UnityCommandLineSpec.groovy
Labels: update, atlas-stream

#119 Fix removed PropertyLookup API
  src/main/groovy/wooga/gradle/unity/utils/PropertyLookup.groovy
Labels: fix, atlas-stream

#122 Add missing internal annotations
  src/main/groovy/wooga/gradle/unity/traits/UnitySpec.groovy
Labels: update, atlas-stream

#121 Fix logToStdout when logPath is also set
  src/integrationTest/groovy/wooga/gradle/unity/UnityIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/utils/PropertyQueryTaskWriter.groovy
  src/main/groovy/wooga/gradle/unity/UnityTask.groovy
  src/main/groovy/wooga/gradle/unity/traits/UnityCommandLineSpec.groovy
Labels: fix, atlas-stream

#125 Pin version of com.wooga.gradle:gradle-commons [ATLAS-268]
  build.gradle
Labels: fix, atlas-stream

#124 Fix PlayMode test tasks are executed as EditMode
  src/integrationTest/groovy/wooga/gradle/unity/tasks/TestTaskIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
Labels: fix, atlas-stream

#126 Add basic UPM package install logic
  build.gradle
  src/integrationTest/groovy/wooga/gradle/unity/UnityPluginIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/unity/UnityTaskIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/unity/tasks/AddUPMPackagesTaskIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/unity/testutils/GradleRunResult.groovy
  src/integrationTest/groovy/wooga/gradle/utils/PropertyQueryTaskWriter.groovy
  src/main/groovy/wooga/gradle/unity/UnityPlugin.groovy
  src/main/groovy/wooga/gradle/unity/UnityPluginExtension.groovy
  src/main/groovy/wooga/gradle/unity/tasks/AddUPMPackages.groovy
  src/main/groovy/wooga/gradle/unity/tasks/GenerateSolution.groovy
  src/test/groovy/wooga/gradle/unity/UnityPluginTest.groovy
Labels: add, atlas-stream
